language: ruby
script: 'true'
gemfile: Travis_Gemfile

install:
  bundle install --jobs=3 --retry=3

before_script:
  - cp config/travis_database.yml config/database.yml

script:
  - rake db:migrate RAILS_ENV=test
  - rake test:models
